# -*- coding: utf-8 -*-
"""finance_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLLqhQZW4EYeShytx8a3IM-fiiky0xgk
"""


import os
from dotenv import load_dotenv
import json
from langgraph.graph import StateGraph, END
from typing import TypedDict, Annotated
from pydantic import BaseModel
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_openai import AzureChatOpenAI



load_dotenv()

def initialize_llm():
  return AzureChatOpenAI(      
      azure_deployment=os.getenv("AZURE_OPENAI_DEPLOYMENT"),
      api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
      temperature=0.0,
      azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT")
  )

tavily_api_key = os.getenv("TAVILY_API_KEY")
from tavily import TavilyClient
tavily_client = TavilyClient(api_key=tavily_api_key)

model = initialize_llm()
print(model)





from io import StringIO
import pandas as pd
from typing import List

class AgentState(TypedDict):
    task: str
    competitors: List[str]
    csv_file: str
    financial_data: str
    analysis: str
    competitor_data: str
    comparison: str
    feedback: str
    report: str
    content: List[str]
    revision_number: int
    max_revisions: int

class Queries(BaseModel):
    queries: List[str]

GATHER_FINANCIALS_PROMPT = """You are an expert financial analyst. Gather the financial data for the given company. Provide detailed financial data."""
ANALYZE_DATA_PROMPT = """You are an expert financial analyst. Analyze the provided financial data and provide detailed insights and analysis."""
RESEARCH_COMPETITORS_PROMPT = """You are a researcher tasked with providing information about similar companies for performance comparison. Generate a list of search queries to gather relevant information. Only generate 3 queries max."""
COMPETE_PERFORMANCE_PROMPT = """You are an expert financial analyst. Compare the financial performance of the given company with its competitors based on the provided data.
**MAKE SURE TO INCLUDE THE NAMES OF THE COMPETITORS IN THE COMPARISON.**"""
FEEDBACK_PROMPT = """You are a reviewer. Provide detailed feedback and critique for the provided financial comparison report. Include any additional information or revisions needed."""
WRITE_REPORT_PROMPT = """You are a financial report writer. Write a comprehensive financial report based on the analysis, competitor research, comparison, and feedback provided."""
RESEARCH_CRITIQUE_PROMPT = """You are a researcher tasked with providing information to address the provided critique. Generate a list of search queries to gather relevant information. Only generate 3 queries max."""

from langchain_core.messages import HumanMessage, SystemMessage

def gather_financials_node(state:AgentState):
  csv_file = state["csv_file"]
  df = pd.read_csv(StringIO(csv_file))

  financial_data_str = df.to_string(index=False)

  # Combine the financial data string with the task
  combined_content = (
        f"{state['task']}\n\nHere is the financial data:\n\n{financial_data_str}"
    )

  messages = [
        SystemMessage(content=GATHER_FINANCIALS_PROMPT),
        HumanMessage(content=combined_content),
    ]

  response = model.invoke(messages)
  return {"financial_data": response.content}

def analyze_data_node(state: AgentState):
  messages = [
        SystemMessage(content=ANALYZE_DATA_PROMPT),
        HumanMessage(content=state["financial_data"]),
    ]

  response = model.invoke(messages)
  return {"analysis": response.content}

def research_competitors_node(state: AgentState):
    content = state["content"] or []
    for competitor in state["competitors"]:
        queries = model.with_structured_output(Queries).invoke(
            [
                SystemMessage(content=RESEARCH_COMPETITORS_PROMPT),
                HumanMessage(content=competitor),
            ]
        )
        query_list = queries.queries if hasattr(queries, "queries") else queries["queries"] # type: ignore
        for q in query_list:
            response = tavily_client.search(query=q, max_results=2)
            for r in response["results"]:
                content.append(r["content"])
    return {"content": content}

def compare_performance_node(state: AgentState):
    content = "\n\n".join(state["content"] or [])

    user_message = HumanMessage(
        content=f"{state['task']}\n\nHere is the financial analysis:\n\n{state['analysis']}"
    )
    messages = [
        SystemMessage(content=COMPETE_PERFORMANCE_PROMPT.format(content=content)),
        user_message,
    ]
    response = model.invoke(messages)
    return {
        "comparison": response.content,
        "revision_number": state.get("revision_number", 1) + 1,
    }

def research_critique_node(state: AgentState):
    queries = model.with_structured_output(Queries).invoke(
        [
            SystemMessage(content=RESEARCH_CRITIQUE_PROMPT),
            HumanMessage(content=state["feedback"]),
        ]
    )
    content = state["content"] or []
    query_list = queries.queries if hasattr(queries, "queries") else queries["queries"] # type: ignore
    for q in query_list:
        response = tavily_client.search(query=q, max_results=2)
        for r in response["results"]:
            content.append(r["content"])
    return {"content": content}

def collect_feedback_node(state: AgentState):
    messages = [
        SystemMessage(content=FEEDBACK_PROMPT),
        HumanMessage(content=state["comparison"]),
    ]
    response = model.invoke(messages)
    return {"feedback": response.content}

def write_report_node(state: AgentState):
    messages = [
        SystemMessage(content=WRITE_REPORT_PROMPT),
        HumanMessage(content=state["comparison"]),
    ]
    response = model.invoke(messages)
    return {"report": response.content}

def should_continue(state):
    if state["revision_number"] > state["max_revisions"]:
        return END
    return "collect_feedback"

builder = StateGraph(AgentState)

builder.add_node("gather_financials", gather_financials_node)
builder.add_node("analyze_data", analyze_data_node)
builder.add_node("research_competitors", research_competitors_node)
builder.add_node("compare_performance", compare_performance_node)
builder.add_node("collect_feedback", collect_feedback_node)
builder.add_node("research_critique", research_critique_node)

builder.add_node("write_report", write_report_node)


builder.set_entry_point("gather_financials")

builder.add_conditional_edges(
    "compare_performance",
    should_continue,
    {END: END, "collect_feedback": "collect_feedback"},
)

builder.add_edge("gather_financials", "analyze_data")
builder.add_edge("analyze_data", "research_competitors")
builder.add_edge("research_competitors", "compare_performance")
builder.add_edge("collect_feedback", "research_critique")
builder.add_edge("research_critique", "compare_performance")
builder.add_edge("compare_performance", "write_report")

graph = builder.compile()



# import streamlit as st

# def main():
#     st.title("Financial Performance Reporting Agent")
#     task = st.text_input(
#         "Enter the task:",
#         "Analyze the financial performance of our company HCLTech compared to competitors",
#     )
#     competitors = st.text_area("Enter competitor names (one per line):").split("\n")
#     max_revisions = st.number_input("Max Revisions", min_value=1, value=2)
#     uploaded_file = st.file_uploader(
#         "Upload a CSV file with the company's financial data", type=["csv"]
#     )
#     if uploaded_file is not None and st.button("Start Analysis"):
#         csv_data = uploaded_file.getvalue().decode("utf-8")

#         # Initialize state with all required keys

#         initial_state = {

#             "task": task,
#             "competitors": [comp.strip() for comp in competitors if comp.strip()],
#             "csv_file": csv_data,
#             "max_revisions": max_revisions,
#             "revision_number": 1,
#             # Add these initialized keys
#             "content": [],
#             "financial_data": "",
#             "analysis": "",
#             "competitor_data": "",
#             "comparison": "",
#             "feedback": "",
#             "report": "",
#         }

#         state_placeholder = st.empty()

#         thread = {"configurable": {"thread_id": "1"}}

#         try:
#             final_state = None
#             for s in graph.stream(initial_state):  # type: ignore
#                 with state_placeholder.container():
#                     st.write("Current State:", s)
#                 final_state = s

#             if final_state and "report" in final_state:
#                 st.subheader("Final Report")
#                 st.markdown(final_state["report"])

#         except Exception as e:
#             st.error(f"An error occurred: {str(e)}")

# if __name__ == "__main__":
#     main()

# Debugging code to run pipeline without UI
def debug_main():
    # Provide a sample CSV string for debugging
    csv_data = """Year,Revenue,Profit\n2022,100000,10000\n2023,120000,15000"""
    initial_state = {
        "task": "Analyze the financial performance of our company HCL compared to competitors",
        "competitors": ["TCS", "Infosys"],
        "csv_file": csv_data,
        "max_revisions": 2,
        "revision_number": 1,
        "content": [],
        "financial_data": "",
        "analysis": "",
        "competitor_data": "",
        "comparison": "",
        "feedback": "",
        "report": "",
    }
    print("Initial State:", initial_state)
    try:
        final_state = None
        for s in graph.stream(initial_state):  # type: ignore
            print("Current State:", s)
            final_state = s
        if final_state and "report" in final_state:
            print("\nFinal Report:\n", final_state["report"])
    except Exception as e:
        print(f"An error occurred: {str(e)}")

if __name__ == "__main__":
    debug_main()
