from langchain.chains.question_answering import load_qa_chain
from langchain_community.vectorstores import Qdrant
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms import Ollama  # or your preferred LLM
from qdrant_client import QdrantClient
from langchain_openai import AzureChatOpenAI
import os
from pydantic import BaseModel, Field
from typing import List, Optional

class Source(BaseModel):
    """Represents a single source document."""
    content: str = Field(..., description="The content of the source document.")
    metadata: dict = Field(default_factory=dict, description="The metadata of the source document.")
    source: Optional[str] = Field(None, description="The source of the document.")

class RAGResponse(BaseModel):
    """The response model for a RAG query."""
    question: str = Field(..., description="The question that was asked.")
    answer: str = Field(..., description="The answer generated by the RAG pipeline.")
    sources: List[Source] = Field(..., description="A list of source documents used to generate the answer.")
    num_sources: int = Field(..., description="The number of source documents used.")

class RAGQueryEngine:
    """RAG Query Engine using Qdrant vector store"""
   
    def __init__(self, collection_name: str = "rag_documents",
                 qdrant_host: str = "localhost", qdrant_port: int = 6333):
        self.collection_name = collection_name
        self.qdrant_client = QdrantClient(host=qdrant_host, port=qdrant_port)
        self.embeddings = HuggingFaceEmbeddings(
            model_name="sentence-transformers/all-MiniLM-L6-v2"
        )
        self.vectorstore = None
        self.qa_chain = None
        self.content_payload_key = "content"
        self.metadata_payload_key = "metadata"
        self._setup_retrieval_chain()
   
    def _setup_retrieval_chain(self):
        """Setup the RetrievalQA chain with Qdrant"""
        try:
            # Initialize Qdrant vector store with custom payload keys
            self.vectorstore = Qdrant(
                client=self.qdrant_client,
                collection_name=self.collection_name,
                embeddings=self.embeddings,
                content_payload_key=self.content_payload_key,
                metadata_payload_key=self.metadata_payload_key,
            )
           
            # Initialize LLM
            llm = AzureChatOpenAI(
                deployment_name=os.environ["deployment_name"],
                openai_api_key=os.environ["openai_api_key"],
                azure_endpoint=os.environ["azure_endpoint"],
                openai_api_version=os.environ["openai_api_version"],
                temperature=0.2,
            )

            # Create a question-answering chain
            self.qa_chain = load_qa_chain(
                llm=llm,
                chain_type="stuff",
                verbose=True
                #return_source_documents=True

            )
           
            print(f"✅ RetrievalQA chain setup successful with collection: {self.collection_name}")
           
        except Exception as e:
            print(f"❌ Error setting up RetrievalQA chain: {str(e)}")
            raise
   
    def query(self, question: str) -> dict:
        """Query the RAG system and return a structured response."""
        if not self.qa_chain:
            raise ValueError("QA chain not initialized")
       
        try:
            # Manually retrieve documents to filter them
            retriever = self.vectorstore.as_retriever(
                search_type="similarity",
                search_kwargs={"k": 5}
            )
            source_docs = retriever.get_relevant_documents(question)
            
            # Filter out documents that are None or have empty content
            valid_docs = [doc for doc in source_docs if doc.page_content and doc.page_content.strip()]
            
            if not valid_docs:
                # If no valid documents are found, return a specific response
                rag_response = RAGResponse(
                    question=question,
                    answer="No relevant information found with content to answer the question.",
                    sources=[],
                    num_sources=0
                )
                return rag_response.model_dump()

            # Run the QA chain with the filtered documents
            response = self.qa_chain.invoke(
                {"input_documents": valid_docs, "question": question},
                return_only_outputs=True
            )
            answer = response["output_text"]
           
            # Create a list of Source objects from the valid documents
            sources = [
                Source(
                    content=doc.page_content,
                    metadata=doc.metadata,
                    source=doc.metadata.get("source", "Unknown")
                ) for doc in valid_docs
            ]
           
            # Create and validate the RAGResponse
            rag_response = RAGResponse(
                question=question,
                answer=answer,
                sources=sources,
                num_sources=len(sources)
            )
           
            return rag_response.model_dump()
           
        except Exception as e:
            print(f"❌ Error during query: {str(e)}")
            # Return a structured error response
            error_response = RAGResponse(
                question=question,
                answer=f"Error processing query: {str(e)}",
                sources=[],
                num_sources=0
            )
            return error_response.model_dump()
   
    def verify_connection(self):
        """Verify Qdrant connection and collection status"""
        try:
            collection_info = self.qdrant_client.get_collection(self.collection_name)
            print(f"✅ Collection '{self.collection_name}' found")
            print(f"   Points count: {collection_info.points_count}")
            print(f"   Status: {collection_info.status}")
            return True
        except Exception as e:
            print(f"❌ Connection verification failed: {str(e)}")
            return False
 
 
def main():
    """Example usage of the RAG Query Engine"""
   
    # Initialize the RAG query engine
    rag_engine = RAGQueryEngine(collection_name="doc_chunk_embeddings")
   
    # Verify connection
    if not rag_engine.verify_connection():
        print("Failed to connect to Qdrant. Please check your setup.")
        return
   
    # Example questions
    questions = [
        "What are RAG: Large Language Model Optimization?"             
    ]
   
    print("\n" + "="*60)
    print("RAG QUERY ENGINE - TESTING")
    print("="*60)
   
    for question in questions:
        print(f"\n🔍 Question: {question}")
        print("-" * 50)
       
        # Query the system
        result = rag_engine.query(question)
       
        print(f"💡 Answer: {result['answer']}")
        print(f"📚 Sources used: {result['num_sources']}")
       
        if result['sources']:
            print("\n📖 Source Details:")
            for i, source in enumerate(result['sources'][:5], 1):  # Show first 2 sources
                print(f"   {i}. Source: {source['source']}")
                print(f"      Content: {source['content']}")
       
        print("\n" + "-"*50)
 

 
if __name__ == "__main__":
    main()
