import os
import logging
import time
from dotenv import load_dotenv
from azure.monitor.opentelemetry import configure_azure_monitor
import streamlit as st
from typing import List, Optional
from pydantic import BaseModel, Field
from qdrant_client import QdrantClient
from langchain_community.vectorstores import Qdrant
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_openai import AzureChatOpenAI
from langchain.chains import RetrievalQA
from langchain_core.documents import Document
from langchain.retrievers import BM25Retriever, EnsembleRetriever
from sentence_transformers.cross_encoder import CrossEncoder
from opencensus.stats import stats as stats_module
from opencensus.stats import measure as measure_module
from opencensus.stats import view as view_module
from opencensus.stats import aggregation as aggregation_module
from opencensus.tags import tag_map as tag_map_module
from opencensus.ext.azure.metrics_exporter import new_metrics_exporter
from opencensus.ext.azure.log_exporter import AzureLogHandler
#from langchain.callbacks.tracers import LangChainTracer
from langsmith import traceable
import urllib.parse

#tracer = LangChainTracer(project_name="RAG Retriever")
class Source(BaseModel):
    """Represents a single source document."""
    content: str = Field(..., description="The content of the source document.")
    metadata: dict = Field(default_factory=dict, description="The metadata of the source document.")
    source: Optional[str] = Field(None, description="The source of the document.")

class RAGResponse(BaseModel):
    """The response model for a RAG query."""
    question: str = Field(..., description="The question that was asked.")
    answer: str = Field(..., description="The answer generated by the RAG pipeline.")
    sources: List[Source] = Field(..., description="A list of source documents used to generate the answer.")
    num_sources: int = Field(..., description="The number of source documents used.")

class RAGQueryEngine:
    """RAG Query Engine using Qdrant vector store"""
    load_dotenv()
    #region Init & Setup
    def __init__(self, collection_name: str = "rag_collection",
                 qdrant_host: str = "localhost", qdrant_port: int = 6333):
        self.collection_name = collection_name
        qdrant = QdrantClient(
            url=os.environ.get("qdrant-url"),
            api_key=os.environ.get("qdrant-api-key")
        )

        self.qdrant_client = qdrant
        #self.qdrant_client = QdrantClient(host=qdrant_host, port=qdrant_port)
        self.embeddings = HuggingFaceEmbeddings(
            model_name="sentence-transformers/all-MiniLM-L6-v2",
            model_kwargs={'device': 'cpu'}
        )
        self.vectorstore = None
        self.qa_chain = None
        self.content_payload_key = "content"
        self.cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')
        # Setup logging and metrics
        self.logger = logging.getLogger("RAGMetricsLogger")
        self.logger.setLevel(logging.INFO)
        self.metrics_enabled = False
        self._setup_opencensus_logging_and_metrics()
        self._setup_retrieval_chain()

    def _setup_opencensus_logging_and_metrics(self):
        """
        Setup OpenCensus logging and metrics exporters.
        """
        azure_key = os.environ.get("AZURE_LOG_INSTRUMENTATION_KEY")
        self.stats = None
        self.view_manager = None
        self.stats_recorder = None
        self.exporter = None
        if azure_key:
            try:
                self._add_azure_log_handler(azure_key)
                self._init_opencensus_stats_exporter(azure_key)
                self._register_metrics()
                self.metrics_enabled = True
            except Exception as e:
                self.logger.warning(
                    f"Azure metrics setup failed: {e}"
                )
                self.metrics_enabled = False
                self.stats = None
                self.view_manager = None
                self.stats_recorder = None
                self.exporter = None
        else:
            self.logger.addHandler(logging.StreamHandler())
            self.stats = None
            self.view_manager = None
            self.stats_recorder = None
            self.exporter = None

    def _add_azure_log_handler(self, azure_key):
        """
        Add AzureLogHandler to logger.
        """
        handler = AzureLogHandler(connection_string=azure_key)
        self.logger.addHandler(handler)

    def _init_opencensus_stats_exporter(self, azure_key):
        """
        Initialize OpenCensus stats, view manager, stats recorder, and exporter.
        """
        self.stats = stats_module.stats
        self.view_manager = self.stats.view_manager
        self.stats_recorder = self.stats.stats_recorder
        self.exporter = new_metrics_exporter(
            connection_string=f"{azure_key}"
        )
        self.view_manager.register_exporter(self.exporter)

    def _register_metrics(self):
        # Define measures
        self.retrieval_latency = measure_module.MeasureFloat("retrieval_latency", "Time to fetch chunks", "ms")
        self.chunks_retrieved = measure_module.MeasureInt("chunks_retrieved", "Chunks retrieved per query", "count")
        self.rerank_latency = measure_module.MeasureFloat("rerank_latency", "Re-ranking latency", "ms")
        self.llm_latency = measure_module.MeasureFloat("llm_latency", "LLM response latency", "ms")
        self.token_usage = measure_module.MeasureInt("token_usage", "Token usage per query", "tokens")
        self.response_length = measure_module.MeasureInt("response_length", "Response length", "tokens")

        # Register views
        views = [
            view_module.View("retrieval_latency_view", "Retrieval latency", [], self.retrieval_latency, aggregation_module.LastValueAggregation()),
            view_module.View("chunks_retrieved_view", "Chunks retrieved", [], self.chunks_retrieved, aggregation_module.SumAggregation()),
            view_module.View("rerank_latency_view", "Re-ranking latency", [], self.rerank_latency, aggregation_module.LastValueAggregation()),
            view_module.View("llm_latency_view", "LLM latency", [], self.llm_latency, aggregation_module.LastValueAggregation()),
            view_module.View("token_usage_view", "Token usage", [], self.token_usage, aggregation_module.SumAggregation()),
            view_module.View("response_length_view", "Response length", [], self.response_length, aggregation_module.LastValueAggregation()),
        ]
        if self.view_manager is not None:
            for v in views:
                self.view_manager.register_view(v)

    def _setup_retrieval_chain(self):
        """
        Sets up the RetrievalQA chain using a hybrid retrieval approach that combines Qdrant vector search and BM25 keyword search.
        """
        try:
            self.logger.info("Initializing Qdrant vector store and retrievers...")
            self._init_vectorstore()
            all_docs = self._fetch_all_documents_for_bm25()
            bm25_retriever = self._init_bm25_retriever(all_docs)
            vector_retriever = self.vectorstore.as_retriever(search_kwargs={"k": 10})
            hybrid_retriever = self._get_hybrid_retriever(vector_retriever, bm25_retriever)
            llm = self._init_llm()
            self.qa_chain = RetrievalQA.from_chain_type(
                llm=llm,
                chain_type="stuff",
                retriever=hybrid_retriever,
                return_source_documents=True,
                verbose=True
            )
            self.logger.info(f"RetrievalQA hybrid chain setup successful with collection: {self.collection_name}")
        except Exception as e:
            self.logger.error(f"Error setting up RetrievalQA chain: {str(e)}")
            raise

    def _init_vectorstore(self):
        self.vectorstore = Qdrant(
            client=self.qdrant_client,
            collection_name=self.collection_name,
            embeddings=self.embeddings,
            content_payload_key=self.content_payload_key
        )

    def _fetch_all_documents_for_bm25(self):
        all_docs = []
        try:
            points, _ = self.qdrant_client.scroll(
                collection_name=self.collection_name,
                limit=10000
            )
            for pt in points:
                content = pt.payload.get(self.content_payload_key, "")
                meta = pt.payload.copy()
                all_docs.append(Document(page_content=content, metadata=meta))
            self.logger.info(f"Fetched {len(all_docs)} documents for BM25Retriever.")
        except Exception as e:
            self.logger.warning(f"Could not fetch all docs for BM25: {e}")
        return all_docs

    def _init_bm25_retriever(self, all_docs):
        bm25_retriever = None
        self.bm25_retriever = None
        if all_docs:
            bm25_retriever = BM25Retriever.from_documents(all_docs, k=10)
            self.bm25_retriever = bm25_retriever
            self.logger.info("BM25Retriever initialized.")
        return bm25_retriever

    def _get_hybrid_retriever(self, vector_retriever, bm25_retriever):
        if bm25_retriever:
            hybrid_retriever = EnsembleRetriever(
                retrievers=[vector_retriever, bm25_retriever],
                weights=[0.5, 0.5]
            )
            self.logger.info("Hybrid (Ensemble) retriever initialized.")
        else:
            hybrid_retriever = vector_retriever
            self.logger.info("Only vector retriever initialized.")
        return hybrid_retriever

    def _init_llm(self):
        return AzureChatOpenAI(
            deployment_name=os.environ["deployment_name"],
            openai_api_key=os.environ["openai_api_key"],
            azure_endpoint=os.environ["azure_endpoint"],
            openai_api_version=os.environ["openai_api_version"],
            temperature=0.2,
        )
    #endregion

    #region Query & Search
    @traceable
    def search(self, question: str) -> dict:
        """
        Query the RAG (Retrieval-Augmented Generation) system with a given question and return a structured response.
        """
        if not self.qa_chain:
            raise ValueError("QA chain not initialized")

        try:
            tag_map = tag_map_module.TagMap()
            self.metrics_enabled = True
            self.logger.info(f"Received query: {question}")

            # Retrieval
            #start_retrieval = time.time()
            response = self.qa_chain.invoke({"query": question})
            #retrieval_time = (time.time() - start_retrieval) * 1000
            #self._record_metric(self.retrieval_latency, retrieval_time, tag_map)

            source_chunks = response["source_documents"]
            #self._record_metric(self.chunks_retrieved, len(source_chunks), tag_map)
            self.logger.info(f"Retrieved {len(source_chunks)} candidate chunks from the Retrieval QA chain.")

            # Enrich metadata
            self._enrich_source_chunks_metadata(source_chunks)

            # Rerank
            top_sortedchunks, rerank_time = self._rerank_chunks(question, source_chunks)
            #self._record_metric(self.rerank_latency, rerank_time, tag_map)

            # LLM answer
            start_llm = time.time()
            answer = self.qa_chain.combine_documents_chain.run({
                "input_documents": top_sortedchunks,
                "question": question
            })

            # llm_time = (time.time() - start_llm) * 1000
            # self._record_metric(self.llm_latency, llm_time, tag_map)
            # self._record_metric(self.token_usage, len(question.split()) + len(answer.split()), tag_map)
            # self._record_metric(self.response_length, len(answer), tag_map)

            sources = [
                Source(
                    content=doc.page_content,
                    metadata=dict(doc.metadata) if doc.metadata else {},
                    source=(doc.metadata.get("source") if doc.metadata and "source" in doc.metadata else "Unknown")
                ) for doc in top_sortedchunks
            ]

            rag_response = RAGResponse(
                question=question,
                answer=answer,
                sources=sources,
                num_sources=len(sources)
            )
            self.logger.info(f"Returning answer with {len(sources)} sources.")
            return rag_response.model_dump()

        except Exception as e:
            self.logger.error(f"Error during query: {str(e)}")
            error_response = RAGResponse(
                question=question,
                answer=f"Error processing query: {str(e)}",
                sources=[],
                num_sources=0
            )
            return error_response.model_dump()

    # def _record_metric(self, metric, value, tag_map):
    #     if self.metrics_enabled and self.stats_recorder and metric:
    #         mmap = self.stats_recorder.new_measurement_map()
    #         if mmap:
    #             if isinstance(value, float):
    #                 mmap.measure_float_put(metric, value)
    #             else:
    #                 mmap.measure_int_put(metric, value)
    #             mmap.record(tag_map)

    def _enrich_source_chunks_metadata(self, source_chunks):
        for doc in source_chunks:
            chunk_id = doc.metadata.get('chunk_id') or doc.metadata.get('_id')
            if chunk_id:
                try:
                    points = self.qdrant_client.retrieve(
                        collection_name=self.collection_name,
                        ids=[chunk_id]
                    )
                    if points and hasattr(points[0], 'payload') and isinstance(points[0].payload, dict):
                        doc.metadata.update(points[0].payload)
                except Exception as e:
                    self.logger.warning(f"Could not fetch payload for chunk_id {chunk_id}: {e}")

    def _rerank_chunks(self, question, source_chunks):
        self.logger.info(f"Reranking {len(source_chunks)} candidate chunks using cross-encoder.")
        start_rerank = time.time()
        cross_inp = [[question, doc.page_content] for doc in source_chunks]
        cross_scores = self.cross_encoder.predict(cross_inp)
        scored_chunks = list(zip(cross_scores, source_chunks))
        scored_chunks.sort(key=lambda x: x[0], reverse=True)
        top_sortedchunks = [doc for score, doc in scored_chunks[:5]]
        self.logger.info(f"Top 5 chunks selected after reranking")
        rerank_time = (time.time() - start_rerank) * 1000
        return top_sortedchunks, rerank_time
    #endregion

    #region Utility
    def verify_connection(self):
        """Verify Qdrant connection and collection status"""
        try:
            collection_info = self.qdrant_client.get_collection(self.collection_name)
            print(f"✅ Collection '{self.collection_name}' found")
            print(f"   Points count: {collection_info.points_count}")
            print(f"   Status: {collection_info.status}")
            return True
        except Exception as e:
            print(f"❌ Connection verification failed: {str(e)}")
            return False
    #endregion
 
 
def run_streamlit_app():
    """Streamlit interface for the RAG Query Engine"""
    st.title("Document Search App")

    try:
        # Initialize the RAG query engine
        rag_engine = RAGQueryEngine(collection_name="rag_collection")
    except Exception as e:
        st.error(f"Failed to initialize RAG engine: {e}")
        return

    # Verify connection to Qdrant
    if not rag_engine.verify_connection():
        st.error("Failed to connect to Qdrant. Please check your setup.")
        return

    # Get user input
    question = st.text_input("Enter your question:")

    if st.button("Get Answer"):
        if question:
            with st.spinner("Searching for answer..."):
                result = rag_engine.search(question)
            
            st.subheader("Answer")
            st.write(result['answer'])
            
            st.subheader("Sources")
            _display_sources_streamlit(result['sources'])
        else:
            st.warning("Please enter a question.")

def _display_sources_streamlit(sources):
    """
    Display unique filenames and URLs in Streamlit UI.
    """
    if sources:
        seen = set()
        for source in sources:
            file_path = source['metadata'].get('file_path', 'Unknown')
            if file_path != 'Unknown':
                filename = file_path.split("/")[-1] if "/" in file_path else file_path
                url = urllib.parse.quote(file_path, safe=':/')
                if (filename, url) not in seen:
                    seen.add((filename, url))
                    st.markdown(f'<a href="{url}" title="{file_path}">{filename}</a>', unsafe_allow_html=True)
    else:
        st.write("No sources found.")

if __name__ == "__main__":
     run_streamlit_app()
#     try:
#         rag_engine = RAGQueryEngine(collection_name="rag_collection")
#         if rag_engine.verify_connection():
#             question = "what is Optimized policy compilation for faster decisions?"
#             print(f"Querying with: '{question}'")
#             result = rag_engine.search(question)
#             print("\nAnswer:")
#             print(result['answer'])
#             print(f"\nSources ({result['num_sources']} found):")
#             if result['sources']:
#                 for i, source in enumerate(result['sources'], 1):
#                     print(f"  Source {i}:")
#                     print(f"    File Path: {source['metadata'].get('file_path', 'N/A')}")
#                     print(f"    Content: {source['content']}")
#             else:
#                 print("No sources found.")
#     except Exception as e:
#         print(f"An error occurred: {e}")
#                 print("No sources found.")
#     except Exception as e:
#         print(f"An error occurred: {e}")
