import os
import logging
import time
from dotenv import load_dotenv
import streamlit as st
from typing import List, Optional
from pydantic import BaseModel, Field
from qdrant_client import QdrantClient
from langchain_community.vectorstores import Qdrant
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_openai import AzureChatOpenAI
from langchain.chains import RetrievalQA
from langchain_core.documents import Document
from langchain.retrievers import BM25Retriever, EnsembleRetriever
from sentence_transformers.cross_encoder import CrossEncoder
from langsmith import traceable
import urllib.parse

#tracer = LangChainTracer(project_name="RAG Retriever")
class Source(BaseModel):
    """Represents a single source document."""
    content: str = Field(..., description="The content of the source document.")
    metadata: dict = Field(default_factory=dict, description="The metadata of the source document.")
    source: Optional[str] = Field(None, description="The source of the document.")

class RAGResponse(BaseModel):
    """The response model for a RAG query."""
    question: str = Field(..., description="The question that was asked.")
    answer: str = Field(..., description="The answer generated by the RAG pipeline.")
    sources: List[Source] = Field(..., description="A list of source documents used to generate the answer.")
    num_sources: int = Field(..., description="The number of source documents used.")

class RAGQueryEngine:
    """RAG Query Engine using Qdrant vector store"""
    load_dotenv()
    #region Init & Setup
    def __init__(self, collection_name: str = "rag_collection",
                 qdrant_host: str = "localhost", qdrant_port: int = 6333):
        self.collection_name = collection_name
        qdrant = QdrantClient(
            url=os.environ.get("qdrant-url"),
            api_key=os.environ.get("qdrant-api-key")
        )

        self.qdrant_client = qdrant
        #self.qdrant_client = QdrantClient(host=qdrant_host, port=qdrant_port)
        self.embeddings = HuggingFaceEmbeddings(
            model_name="sentence-transformers/all-MiniLM-L6-v2",
            model_kwargs={'device': 'cpu'}
        )
        self.vectorstore = None
        self.qa_chain = None
        self.content_payload_key = "content"
        self.cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')
        # Setup logging and metrics
        self.logger = logging.getLogger("RAGMetricsLogger")
        self.logger.setLevel(logging.INFO)
        self.metrics_enabled = False        
        self._setup_retrieval_chain()

    def _setup_retrieval_chain(self):
        """
        Sets up the RetrievalQA chain using a hybrid retrieval approach that combines Qdrant vector search and BM25 keyword search.
        """
        try:
            self.logger.info("Initializing Qdrant vector store and retrievers...")
            self._init_vectorstore()
            all_docs = self._fetch_all_documents_for_bm25()
            bm25_retriever = self._init_bm25_retriever(all_docs)
            vector_retriever = self.vectorstore.as_retriever(search_kwargs={"k": 10})
            hybrid_retriever = self._get_hybrid_retriever(vector_retriever, bm25_retriever)
            llm = self._init_llm()
            self.qa_chain = RetrievalQA.from_chain_type(
                llm=llm,
                chain_type="stuff",
                retriever=hybrid_retriever,
                return_source_documents=True,
                verbose=True
            )
            self.logger.info(f"RetrievalQA hybrid chain setup successful with collection: {self.collection_name}")
        except Exception as e:
            self.logger.error(f"Error setting up RetrievalQA chain: {str(e)}")
            raise

    def _init_vectorstore(self):
        self.vectorstore = Qdrant(
            client=self.qdrant_client,
            collection_name=self.collection_name,
            embeddings=self.embeddings,
            content_payload_key=self.content_payload_key
        )

    def _fetch_all_documents_for_bm25(self):
        all_docs = []
        try:
            points, _ = self.qdrant_client.scroll(
                collection_name=self.collection_name,
                limit=10000
            )
            for pt in points:
                content = pt.payload.get(self.content_payload_key, "")
                meta = pt.payload.copy()
                all_docs.append(Document(page_content=content, metadata=meta))
            self.logger.info(f"Fetched {len(all_docs)} documents for BM25Retriever.")
        except Exception as e:
            self.logger.warning(f"Could not fetch all docs for BM25: {e}")
        return all_docs

    def _init_bm25_retriever(self, all_docs):
        bm25_retriever = None
        self.bm25_retriever = None
        if all_docs:
            bm25_retriever = BM25Retriever.from_documents(all_docs, k=10)
            self.bm25_retriever = bm25_retriever
            self.logger.info("BM25Retriever initialized.")
        return bm25_retriever

    def _get_hybrid_retriever(self, vector_retriever, bm25_retriever):
        if bm25_retriever:
            hybrid_retriever = EnsembleRetriever(
                retrievers=[vector_retriever, bm25_retriever],
                weights=[0.5, 0.5]
            )
            self.logger.info("Hybrid (Ensemble) retriever initialized.")
        else:
            hybrid_retriever = vector_retriever
            self.logger.info("Only vector retriever initialized.")
        return hybrid_retriever

    def _init_llm(self):
        return AzureChatOpenAI(
            deployment_name=os.environ["deployment_name"],
            openai_api_key=os.environ["openai_api_key"],
            azure_endpoint=os.environ["azure_endpoint"],
            openai_api_version=os.environ["openai_api_version"],
            temperature=0.2,
        )
    #endregion

    #region Query & Search
    @traceable
    def search(self, question: str) -> dict:
        """
        Query the RAG (Retrieval-Augmented Generation) system with a given question and return a structured response.
        """
        if not self.qa_chain:
            raise ValueError("QA chain not initialized")

        try:
            
            self.metrics_enabled = True
            self.logger.info(f"Received query: {question}")

            # Retrieval
            response = self.qa_chain.invoke({"query": question})           
            source_chunks = response["source_documents"]
            self.logger.info(f"Retrieved {len(source_chunks)} candidate chunks from the Retrieval QA chain.")

            # Enrich metadata
            self._enrich_source_chunks_metadata(source_chunks)
            
            # Rerank
            top_sortedchunks, rerank_time = self._rerank_chunks(question, source_chunks)
            
            # LLM answer
            start_llm = time.time()
            answer = self.qa_chain.combine_documents_chain.run({
                "input_documents": top_sortedchunks,
                "question": question
            })

            sources = [
                Source(
                    content=doc.page_content,
                    metadata=dict(doc.metadata) if doc.metadata else {},
                    source=(doc.metadata.get("source") if doc.metadata and "source" in doc.metadata else "Unknown")
                ) for doc in top_sortedchunks
            ]

            rag_response = RAGResponse(
                question=question,
                answer=answer,
                sources=sources,
                num_sources=len(sources)
            )
            self.logger.info(f"Returning answer with {len(sources)} sources.")
            return rag_response.model_dump()

        except Exception as e:
            self.logger.error(f"Error during query: {str(e)}")
            error_response = RAGResponse(
                question=question,
                answer=f"Error processing query: {str(e)}",
                sources=[],
                num_sources=0
            )
            return error_response.model_dump()

    def _enrich_source_chunks_metadata(self, source_chunks):
        for doc in source_chunks:
            chunk_id = doc.metadata.get('chunk_id') or doc.metadata.get('_id')
            if chunk_id:
                try:
                    points = self.qdrant_client.retrieve(
                        collection_name=self.collection_name,
                        ids=[chunk_id]
                    )
                    if points and hasattr(points[0], 'payload') and isinstance(points[0].payload, dict):
                        doc.metadata.update(points[0].payload)
                except Exception as e:
                    self.logger.warning(f"Could not fetch payload for chunk_id {chunk_id}: {e}")

    def _rerank_chunks(self, question, source_chunks):
        self.logger.info(f"Reranking {len(source_chunks)} candidate chunks using cross-encoder.")
        start_rerank = time.time()
        cross_inp = [[question, doc.page_content] for doc in source_chunks]
        cross_scores = self.cross_encoder.predict(cross_inp)
        scored_chunks = list(zip(cross_scores, source_chunks))
        scored_chunks.sort(key=lambda x: x[0], reverse=True)
        top_sortedchunks = [doc for score, doc in scored_chunks[:5]]
        self.logger.info(f"Top 5 chunks selected after reranking")
        rerank_time = (time.time() - start_rerank) * 1000
        return top_sortedchunks, rerank_time
    #endregion

    #region Utility
    def verify_connection(self):
        """Verify Qdrant connection and collection status"""
        try:
            collection_info = self.qdrant_client.get_collection(self.collection_name)
            print(f"✅ Collection '{self.collection_name}' found")
            print(f"   Points count: {collection_info.points_count}")
            print(f"   Status: {collection_info.status}")
            return True
        except Exception as e:
            print(f"❌ Connection verification failed: {str(e)}")
            return False
    #endregion
 
 
def run_streamlit_app():
    """Streamlit interface for the RAG Query Engine"""
    # Set page config and background color
    st.set_page_config(page_title="Document Search App", layout="centered")
    st.markdown(
        """
        <style>
        body {
            background: #f4f6fb !important;
            font-family: 'Segoe UI', 'Roboto', 'Arial', sans-serif;
        }
        .stApp {
            background: #f4f6fb !important;
        }
        header[data-testid="stHeader"] {
            display: none;
        }
        .block-container {
            margin-top: 0px !important;
            padding-top: 0px !important;
            max-width: 600px;
        }
        .main-card {
            background: #fff;
            border-radius: 18px;
            box-shadow: 0 4px 24px rgba(0,0,0,0.08);
            padding: 32px 32px 24px 32px;
            margin-top: 32px;
        }
        .title {
            font-size: 2.2rem;
            font-weight: 700;
            color: #1a237e;
            margin-bottom: 8px;
            text-align: center;
        }
        .subtitle {
            font-size: 1.1rem;
            color: #455a64;
            margin-bottom: 24px;
            text-align: center;
        }
        .stTextInput>div>input {
            border-radius: 8px;
            border: 1px solid #90caf9;
            padding: 10px;
            font-size: 1rem;
        }
        .stForm .stButton>button {
            background: linear-gradient(90deg,#1976d2 0,#64b5f6 100%);
            color: #fff;
            border-radius: 8px;
            font-weight: 600;
            font-size: 1rem;
            padding: 10px 24px;
            border: none;
            box-shadow: 0 2px 8px rgba(25,118,210,0.08);
        }
        .sources-card {
            background: #f8fbff;
            border-radius: 12px;
            padding: 16px;
            margin-top: 16px;
            box-shadow: 0 2px 8px rgba(25,118,210,0.05);
        }
        .source-link {
            color: #1976d2;
            font-weight: 500;
            text-decoration: none;
            margin-right: 12px;
        }
        .source-link:hover {
            text-decoration: underline;
        }
        </style>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        """
        <div class="main-card">
            <div class="title">🔎 Document Search App</div>
            <div class="subtitle">Ask a question about your documents and get relevant answers with sources.</div>
        </div>
        """,
        unsafe_allow_html=True
    )

    # Show loader while initializing engine and verifying connection
    with st.spinner("Verifying connection..."):
        try:
            rag_engine = RAGQueryEngine(collection_name="rag_collection")
        except Exception as e:
            st.error(f"Failed to initialize RAG engine: {e}")
            return

        # Verify connection to Qdrant
        if not rag_engine.verify_connection():
            st.error("Failed to connect to Qdrant. Please check your setup.")
            return

    # Use a form to group input and button, reducing reruns and UI lag
    with st.form("query_form"):
        question = st.text_input("Enter your question:", help="Type your question and click 'Get Answer'")
        submit = st.form_submit_button("Get Answer")

    if submit:
        if question:
            with st.spinner("Retrieving relevant documents and generating answer..."):
                result = rag_engine.search(question)
            # Render answer and sources in one block
            # Build sources HTML as a string
            sources_html = ""
            if result['answer'].strip().lower() != "i don't know":
                sources_html += '<div class="title" style="font-size:1.2rem; margin-bottom:8px; text-align:left;">Sources</div><div class="sources-card">'
                sources_html += _get_sources_html(result['sources'])
                sources_html += '</div>'
            st.markdown(
                f'<div class="main-card">'
                f'<div class="title" style="text-align:left;">Answer</div>'
                f'<div style="font-size:1.05rem; color:#222; margin-bottom:18px; text-align:left;">{result["answer"]}</div>'
                f'{sources_html}'
                f'</div>',
                unsafe_allow_html=True
            )
        else:
            st.warning("Please enter a question.")


def _get_sources_html(sources):
    """
    Return HTML string for unique filenames and URLs for sources.
    """
    if sources:
        seen = set()
        items = []
        for source in sources:
            file_path = source['metadata'].get('file_path', 'Unknown')
            if file_path != 'Unknown':
                filename = file_path.split("/")[-1] if "/" in file_path else file_path
                url = urllib.parse.quote(file_path, safe=':/')
                if (filename, url) not in seen:
                    seen.add((filename, url))
                    items.append(f'<li><a class="source-link" href="{url}" title="{file_path}" target="_blank">{filename}</a></li>')
        if items:
            return f'<ul style="padding-left:18px; margin:0;">{"".join(items)}</ul>'
        else:
            return "<span style='color:#888;'>No sources found.</span>"
    else:
        return "<span style='color:#888;'>No sources found.</span>"

if __name__ == "__main__":
     run_streamlit_app()



